### ISSUE TITLE
Tutorial website link is broken

### ISSUE THREAD

**Issue by mrburke00** [PaulRegnier/PICAFlow#2]
Hi,

it appears the link to the tutorial is broken in the README. 

Thanks

**Comment by PaulRegnier** [comment]
Hello @mrburke00,

I am very sorry about that, I was performing some maintenance stuff on the website and I forgot to turn on the "coming back soon" screen.

This website should now work normally (force-refresh with Ctrl + F5 if necessary).

Sorry again for the incovenience.
