### ISSUE TITLE
Trouble installing ...

### ISSUE THREAD

**Issue by aldojongejan** [PaulRegnier/PICAFlow#5]
Dear Dr. Regnier,

Yhanks for making this workflow available, but unfortunately I am unable to install the package. Either directly from GitHub or downloading it first and then as local package. I keep stumbling on this error:

* installing *source* package 'PICAFlow' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'PICAFlow':
 .onLoad failed in loadNamespace() for 'PICAFlow', details:
  call: gh::gh("GET /repos/{owner}/{repo}/releases", owner = "PaulRegnier", 
  error: GitHub API error (401): Bad credentials
ℹ Read more at <https://docs.github.com/rest>
Error: loading failed
Execution halted
ERROR: loading failed

Any solution?

kind regards,
Aldo Jongejan

**Comment by PaulRegnier** [comment]
Hello @aldojongejan,

Thank you for your interest in `PICAFlow`!

I just tried to install `PICAFlow` using the above command, and it worked flawlessly:

`devtools::install_github("PaulRegnier/PICAFlow", force = TRUE)`

Have you checked that:
- The `devtools` package is installed and loaded? Use `install.packages("devtools")` then `library("devtools")`
- The installation command you use is properly written?

Please let me know if you manage to install the package.

Have a nice day!

Best regards,

Paul

**Comment by aldojongejan** [comment]
Hi Paul, 
Thanks for your fast reply, but unfortunately it doesn't work for me..
I use 'devtools' and copied your command. R uses my GITHUB_PAT, so that should all be OK.
I do NOT update all the packages, but that doesn't seem to be the problem.

Is there somewhere in the installation a reference to your Github that you can access, but I can not?

```
>devtools::install_github("PaulRegnier/PICAFlow", force = TRUE)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo PaulRegnier/PICAFlow@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                          
 2: CRAN packages only                           
 3: None                                         
 4: Biobase    (2.62.0    -> a3b75b7e1...) [Bioc]
...
54: uwot       (0.1.16    -> 0.2.2       ) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\P002814\AppData\Local\Temp\RtmpYX00qY\remotes4d80226e63b8\PaulRegnier-PICAFlow-b6ebba8/DESCRIPTION' (343ms)
─  preparing 'PICAFlow': (844ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'PICAFlow_1.0.1.tar.gz'
   
Installing package into ‘D:/R/myRLibs/R-4.3.2/library’
(as ‘lib’ is unspecified)
* installing *source* package 'PICAFlow' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'PICAFlow':
 .onLoad failed in loadNamespace() for 'PICAFlow', details:
  call: gh::gh("GET /repos/{owner}/{repo}/releases", owner = "PaulRegnier", 
  error: GitHub API error (401): Bad credentials
ℹ Read more at <https://docs.github.com/rest>
Error: loading failed
Execution halted
ERROR: loading failed
```


Sorry, for the trouble,

Aldo

**Comment by PaulRegnier** [comment]
Hello @aldojongejan,

Hum, that is unusual. I do not use PAT at all for GitHub login, so I don't really know what is going on here.

However, after a quick look on Internet, I found some troubleshooting pages that could be helpful:
- https://forum.posit.co/t/troubleshooting-github-tokens/115489/9
- https://cran.r-project.org/web/packages/gh/vignettes/managing-personal-access-tokens.html

Apparently, some users have had the same problem and managed to fix it by removing then re-entering their own PAT in their R environment.

To maximize the chances to make it work, I also added the possibility (with the `...` ellipsis syntax) to specify any argument of the used functions within the `checkNewVersion()` function, which seems to be the one that throws this error. You could then specify the `.token` argument (or any other) if necessary.

Don't hesitate to let me know if it worked for you or not.

Have a nice day!

Best,

Paul

**Comment by aldojongejan** [comment]
Hi Paul,

Thanks for your help!!
I had thought I had fixed it by adding the new PAT within my R session using the 'credentials' package, but it turned out I had indeed to enter the new PAT in my .Renviron file as well. Now, it works!!

Thanks for your patience and help!

Have a nice day,
Aldo
